### ISSUE TITLE
Code generation

### ISSUE THREAD

**Issue by sheldon-sminq** [tbugrara/dropwizard-jooq#1]
Ho do i use the code generation feature of JooQ with this plugin?  Do i need to have the jooq xml configuration or the yaml config is good enough?

**Comment by tariqkb** [comment]
You'll still have to use the xml to generate the jooq classes. Let me know if you have any other questions!

**Comment by sheldon-sminq** [comment]
Thanks it works well with the maven jooq build plugin. To fetch the latest jooq release i have to just modify the gradle files right?

**Comment by sheldon-sminq** [comment]
It would be great if you could update Jooq to 3.6.1 and also include the jooq-meta package. Thanks

**Comment by tariqkb** [comment]
I updated to jOOQ to 3.6.1 and dropwizard to 0.8.1, thanks for pointing that out. Also added jooq-meta to dependencies so this module provides all jOOQ-related needs. I'm going to close this issue for now, but please feel free to open another if you need anything!

**Comment by tariqkb** [comment]
By the way, these changes are in version 0.1.2, which isn't currently showing up in maven search (usually an hour or two to update), but should be good to directly pull now.
